### ISSUE TITLE
Feature request: routing handler

### ISSUE THREAD

**Issue by worksofliam** [sitemule/ILEastic#1]
Hi

ILEastic is awesome, but there needs to be a way to handle the routing for requests.

For example, I'd like one 'servlet' to be able to handle multiple routes. Right now ILEastic cannot handle routes.

My initial thought is that the endpoint/url of the request could be passed in with the `REQUEST`/`requestDS` struct.

For example:

```
dcl-proc myservlet;

    dcl-pi *n;
        request  likeds(REQUESTDS);
        response likeds(RESPONSEDS);
    end-pi;

    Select;
        When (request.endpoint = '/'); //Index
            il_write(response:'<p>index</p>');
        When (request.endpoint = '/other'); //Index
            OtherHandler(request:response);
    Endsel;

end-proc;
```

What do you think?

Many thanks,
Liam Barry

**Comment by NielsLiisberg** [comment]
Absolutely! I have not made anything in the request yet - please stay tuned. And thank you for your feedback

**Comment by WorksOfLiam** [comment]
As a follow up, I had an idea for routing parts.

For example, if you'd like to make a dynamic rest API: the URL could be split up into parts.

```
getURLPart(request.url:1); //where request.url = '/id/101', would return '101'
```

**Comment by WorksOfLiam** [comment]
Just to keep notes. `request.url` and `request.resource` were both added in 46e327eb5684b67ae610ff3041a6aa4c5e9bc192.

* https://github.com/NielsLiisberg/ILEastic/commit/46e327eb5684b67ae610ff3041a6aa4c5e9bc192#diff-31f80c15f7e9f88d7f242068acadb407R148
* https://github.com/NielsLiisberg/ILEastic/commit/46e327eb5684b67ae610ff3041a6aa4c5e9bc192#diff-31f80c15f7e9f88d7f242068acadb407R160

**Comment by m1h43l** [comment]
Each ILEastic definitely needs to handle multiple endpoints. It would scale really bad if you need to have one service running for each endpoint.

I think we need to split the registering of an endpoint from the starting of the server (as it is now with the il_listen function).

The minimum parts for adding an endpoint should be the address of the endpoint, url and HTTP method.

In modern frameworks the available content types (for the return value) is also part of the routing.

**Comment by m1h43l** [comment]
> For example, if you'd like to make a dynamic rest API: the URL could be split up into parts.

This should be no feature but a default requirement to the framework. It is not possible to build a decent API without accessing the single parts of the URL.

**Comment by NielsLiisberg** [comment]
Partly solved - routing is added, but picking the parameters are still missing

**Comment by NielsLiisberg** [comment]
working on the "parameter pickup" now ...

**Comment by m1h43l** [comment]
Path segments can now be retrieved by index, see il_getRequestSegmentByIndex() . Can we close this issue?

**Comment by NielsLiisberg** [comment]
Yes let's close it: Now there is two options to the solution. Your @m1h43l  il_getRequestSegmentByIndex() and my callback solution with regex. They both server a their own purpose. Great work @m1h43l  !!
