### ISSUE TITLE
Using il_getPathParameter Without Index Returns Wrong Value

### ISSUE THREAD

**Issue by MarkBoyer** [sitemule/ILEastic#111]
I emailed @NielsLiisberg about this issue.  It's was a little difficult to locate and only became apparently when a business partner began rapid firing requests at the same endpoint.  If a second request comes in to the same endpoint invoking the same procedure before the first procedure has time to use il_getPathParameter by name to retrieve values, the second requests values are returned.  Using il_getPathParameter with an index value always returns the correct values.  I believe this has something to do with the two different ways that values are retrieved in the il_getPathParameter procedure based on the number of parameters provided.  I'm not a C developer and this thread thing with RPG is new to me.

**FREE

/// ------------------------------------------------------------------------------------
// PARMERRP - REST API Driver
//
// Start it:
//  SBMJOB CMD(CALL PGM(PARMERRP)) JOB(PARMERRP) JOBQ(QSYSNOMAX) ALWMLTTHD(*YES)
//
// @info: It requires your RPG code to be reentrant and compiled for
//        multithreading. Each client request is handled by a seperate thread.
/// ------------------------------------------------------------------------------------

ctl-opt decEdit('0,') datEdit(*YMD.) main(main);
ctl-opt debug(*yes) bndDir('ILEASTIC');
ctl-opt thread(*CONCURRENT);

// Header file for ILEastic framework
/include SRCFILE,ILEASTIC
// Header file for NOXDB (Thread Memory Functions)
/include SRCFILE,JSONXML

// Program Status Data Structute
dcl-ds pgmStatus PSDS qualified;
    status          *STATUS;
    exceptionCode   char(7)     pos(40);
end-ds;

// Names Constants
dcl-c true          const(*On);
dcl-c false         const(*Off);
dcl-c null          const(-1);
dcl-c lowercase     const('abcdefghijklmnopqrstuvwxyz');
dcl-c uppercase     const('ABCDEFGHIJKLMNOPQRSTUVWXYZ');

// --------------------------------------------------------------------------------------
// Program Entry Point
// --------------------------------------------------------------------------------------
dcl-proc main;

    // ILEastic Configuration Data Structure
    dcl-ds config likeds(il_config);

    // Set port and host values
    config.port = 1302;
    config.host = '*ANY';

    // The resource paths must be entered as a regular expression.
    //
    // Paramter names are in the form {parmName}
    //
    // If none of these endpoints are satified
    // it will return 404 NOT FOUND.

    il_addRoute(config : %paddr($TestParmError) : IL_GET :
       '^/test/{thisValuel}$'
    );

    il_listen(config);

end-proc;

dcl-proc $TestParmError;

    // Procedure Interface
    dcl-pi *n;
        request     likeds(IL_REQUEST);
        response    likeds(IL_RESPONSE);
    end-pi;

    // Local variable declarations
    dcl-s parmValURL1               varchar(78)             inz;
    dcl-s parmValURL2               varchar(78)             inz;
    dcl-s parmValName1              varchar(78)             inz;
    dcl-s parmValName2              varchar(78)             inz;
    dcl-s parmValIndex1             varchar(78)             inz;
    dcl-s parmValIndex2             varchar(78)             inz;

    parmValURL1 = il_getRequestUrl(request);
    parmValName1 = il_getPathParameter (request: 'thisValuel' : ' ');
    parmValIndex1 = il_getPathParameter (request: 'thisValuel' : ' ' : 1);

    // Stop here and run second request from Postman

    parmValURL2 = il_getRequestUrl(request);
    parmValName2 = il_getPathParameter (request: 'thisValuel' : ' ');
    parmValIndex2 = il_getPathParameter (request: 'thisValuel' : ' ' : 1);

    il_responseWrite(response : 'Done...');
    return;

end-proc;

The steps I used are as follows.  I created two very basic requests in Postman.  I started a service job on the submitted program and started debug on the program.  Then:
1) Set break on the line below the "Stop here" comment
2) Send first request from Postman to http://{IP Address or DNS Name}:1302/test/myValue1
3) When debug is shown, remove breakpoint
4) Send second request from Postman to http://{IP Address or DNS Name}:1302/test/myValue2
5) Press F10 in debug (Second Postman request should complete at this time)
6) Use F10 to process remaining lines retrieving values with il_getPathParameter

Review the values and notice that the first set of values, before the second Postman request was sent, the il_getPathParameter without or with the index value show the same values:
![SCR-20221027-b7m](https://user-images.githubusercontent.com/3966735/198332558-7ce6a452-078c-4aae-a0f6-90e6342a57b1.png)

In the second set of values, the value from il_getPathParameter without and with index are different.  Without the index, the value reflects the second request, with the index, the value correctly reflects the value from the first request:
![SCR-20221027-b9b](https://user-images.githubusercontent.com/3966735/198332921-919f8fdc-440b-4863-a24d-7259838ec929.png)

We also have an error being thrown from the cleanupTransaction which uses the same way of identifying the values variables as il_getPathParameter when called without an index value.
![SCR-20221027-bty](https://user-images.githubusercontent.com/3966735/198333678-5380bd39-7393-4338-9d2d-fa364e579a0a.png)
![SCR-20221027-bu5](https://user-images.githubusercontent.com/3966735/198333706-4921354b-e59e-46a2-8c2c-a49605aa217f.png)

**Comment by NielsLiisberg** [comment]
Hello Mark;

We are still investigating; My guess is we have a solution ready tomorrow -
nov 3. .
