### ISSUE TITLE
examples compile fails with CPFA0A9: Object not found.  Object is EN_US.UTF-8.

### ISSUE THREAD

**Issue by jwoehr** [sitemule/ILEastic#113]
Compiling all examples fails, with each failing like this:
```
$ gmake
touch errorlist.txt ;\
setccsid 1252 errorlist.txt;\
liblist -a ILEASTIC;\
setccsid 1252 helloworld.rpgle;\
system -iK "CRTBNDRPG PGM(ILEASTIC/helloworld) SRCSTMF('helloworld.rpgle') OPTION(*NOUNREF) DBGVIEW(*LIST)  OUTPUT(*NONE) INCDIR('./..') TEXT('ILEastic Example Server')" | grep '*RNF' | grep -v '*RNF7031' | sed  "s!*!helloworld.rpgle: &!" ;\

CPFA0A9:  Object not found.  Object is EN_US.UTF-8.
CPFA0A9:  Object not found.  Object is EN_US.UTF-8.
CPFA0A9:  Object not found.  Object is EN_US.UTF-8.
CPFA0A9:  Object not found.  Object is EN_US.UTF-8.
CPI2119:  AUT and USRPRF parameter values were ignored.
CPI2121:  Replaced object HELLOWORLD type *PGM was moved to QRPLOBJ.
RNS9304:  Program HELLOWORLD placed in library ILEASTIC. 00 highest severity. Created on 12/29/22 at 11:24:52.
CPC0904:  Data area RETURNCODE created in library QTEMP.
```
I do have a variable set in my environment: `LC_ALL=EN_US.UTF-8` which is useful in other compilations.
If I unset that variable, the examples compile.

**Comment by NielsLiisberg** [comment]
But it is for sure some locale or ccsid issues. However the program is
created - so the cpfa0a9 is “just” a warning.

Note the RPG code is stored in windows 1252. And is created from that.

Perhaps you can copy / paste the lines below in to a qsh session and a
qp2term session to se if you can’t track er issue. And perhaps even into a
plain qcmd prompt (only the CRTBNDRPG … part of it and use CD to set your
path)

tor. 29. dec. 2022 kl. 17.28 skrev Jack J. Woehr ***@***.***>:

**Comment by m1h43l** [comment]
Works for me. If this is still an issue please reopen this one.
