### ISSUE TITLE
JWT key length issue

### ISSUE THREAD

**Issue by wimjongman** [sitemule/ILEastic#116]
Hey we sometimes run into this issues:

```
CPF9DDD    Escape                  40   03/08/23  11:14:53.654503  QC3HMAC      QSYS        *STMT    JWT         OMS         *STMT
                                     From user . . . . . . . . . :   DPLTOAS400
                                     From module . . . . . . . . :   QC3HMAC
                                     From procedure  . . . . . . :   checkParms__9hmacParmsFRiPv
                                     Statement . . . . . . . . . :   144
                                     To module . . . . . . . . . :   JWT
                                     To procedure  . . . . . . . :   jwt_sign
                                     Statement . . . . . . . . . :   177
                                     Message . . . . :   The key string length is not valid.
                                     Cause . . . . . :   The value specified for the length of key string parameter
                                       or the key string length field in the key description parameter is not
                                       valid.  Refer to the API or CL documentation for valid lengths. Recovery  .
                                       . . :   Correct the value for key string length and try the request again.
```

Is here something obvious I am doing wrong?

**Comment by m1h43l** [comment]
From the IBM i Documenation at https://www.ibm.com/docs/en/i/7.3?topic=ssw_ibm_i_73/apis/qc3calhm.html#keyd0200  ,  see Key type

> 3 -- SHA-256 The minimum length for an SHA-256 HMAC key is 32 bytes.

... and ...

> A key longer than the minimum length does not significantly increase the function strength unless the randomness of the key is considered weak. A key longer than 64 bytes for MD5, SHA-1, and SHA-256, or longer the 128 bytes for SHA-384 and SHA-512 will be hashed before it is used.

So I wouldn't recommend using a key longer than 64 bytes for compatibility reasons (other platforms / libraries may not hash the key if it is longer than 64 bytes).

HTH

**Comment by wimjongman** [comment]
Thanks for the quick response.

Yes, that might be it. I am using a key of only 15 bytes. However, I am still puzzled because, in my test situation it works fine, in a live situation it fails. I am working with the same program on both machines.

**Comment by NielsLiisberg** [comment]
or perhaps the prototype does not have the OPTION(*STRING), that will
terminate the string with x'00'
