### ISSUE TITLE
JWK

### ISSUE THREAD

**Issue by JuanmaAlcudia** [sitemule/ILEastic#117]
It will be good to have an extension to the JWT utils to be able to decrypt a token using a JWK instead of a key as this is the normal case for many token providers.
https://www.rfc-editor.org/rfc/rfc7517

**Comment by NielsLiisberg** [comment]
Thanks for the input.

I will discuss this the group and find a solution.

The JWT is split to atoms in the current support. However JWK is a
different animal

tor. 16. mar. 2023 kl. 22.19 skrev JuanmaAlcudia ***@***.***>:

**Comment by cgvenu** [comment]
JWKS support is added part of latest changes.
caller needs to implement procedure to hit your JWKS end point and retrieve the key.

**Comment by m1h43l** [comment]
To use a JWK(S) stream file for setting the JWT verifying options use the procedure `il_jwt_addVerifyOptionsFromJwks`, see https://github.com/sitemule/ILEastic/blob/master/plugins/jwt/jwtplugin.rpginc#L70 .
