### ISSUE TITLE
JWT verify issue for longer tokens

### ISSUE THREAD

**Issue by marcin-ogon** [sitemule/ILEastic#123]
In jwt.rpgle and jwt_verify procedure variable payloadPos is too small. 
```
dcl-s payloadPos   Packed(3 : 0);
...
payloadPos = %ScanR(utfcomma : token);
```

It should be like it is in jwt_decodePayload procedure
```
dcl-s x int(10);
x = %scan(UTF8_PERIOD : token);
```

**Comment by wimjongman** [comment]
Please make a pull request.

**Comment by NielsLiisberg** [comment]
Will do !!

fre. 29. sep. 2023 kl. 14.23 skrev Wim Jongman ***@***.***>:

**Comment by wimjongman** [comment]
> Will do !! 

This was meant for @marcin-ogon ;)

**Comment by marcin-ogon** [comment]
#128 Ready.
