### ISSUE TITLE
Base64encode gives out values not recognized by JS btoa() function 

### ISSUE THREAD

**Issue by wimjongman** [sitemule/ILEastic#129]
We are using the il_encodebase64 which goes to the JWT proc with the name encodebase64url. In that method, we see a translation from **+** and **/** to **-** and **_**

The resulting base64 is then brought to javascript where the btoa function fails. Why is the translation done like that? Should it not be done the other way around?

![image](https://github.com/sitemule/ILEastic/assets/180969/6b2538c1-235c-45a8-9a23-e4c14478da7d)

https://github.com/sitemule/ILEastic/blob/589bf430f67990098ed7513796c7b1dc3ff65aad/plugins/jwt/jwt.rpgle#L453

**Comment by m1h43l** [comment]
`il_encodeBase64` and `il_decodeBase64` do "just" base64 encoding. You can find the code in the base64 C module.

JWT needs base64 url encoding. And base64 url encoding is pretty much the same as base64 encoding with just the encoded characters / and + replaced with _ and -.

So for me everything seems fine.

**Comment by wimjongman** [comment]
Got it! Thanks, I did not know about the particular URL encoding. That makes total sense.
