### ISSUE TITLE
ILE C compiler (what version?)

### ISSUE THREAD

**Issue by perevs** [sitemule/ILEastic#130]
On the "Installation" paragraph you say: "What you need before you start:"
- IBM i 7.2 TR9 (or higher) - OK
- YUM installed from ACS (to install: git and make-gnu (gmake)) - OK
- ILE RPG compiler - OK
- **ILE C - Pending.** 

At present we have v7r4 but what type of compiler C I need?
![ILE_C_versions](https://github.com/sitemule/ILEastic/assets/148083705/fe47f429-3f46-4364-81a8-a39d8131f6a5)

On the other hand, I guess there's no alternative open source to compile this because it's creating a module inside of the IBM i, right?

CRTCPPMOD MODULE(ILEASTIC/initialize) SRCSTMF('src/initialize.cpp') OPTIMIZE(10) ENUM(*INT) TERASPACE(*YES) STGMDL(*INHERIT) SYSIFCOPT(*IFSIO) INCDIR('/QIBM/include' 'headers/' 'headers/ext/' ) DBGVIEW(*ALL) DEFINE() TGTCCSID(*JOB) TGTRLS(*CURRENT)

This command throws me an error because I haven't ILE C compiler. Any alternative if I haven't the ILE C compiler. Thanks.

Best regards.

**Comment by NielsLiisberg** [comment]
ILEastic is using the option 51  ILE C compiler, however it has a
dependency to noxDb which also is using the  CPP ( option 52).

But as far as I know: if you have product 5770-WDS, then you have
license to all of them. So why not simply install the lot.

**Comment by m1h43l** [comment]
If there are still questions about this topic please reopen this issue.
