### ISSUE TITLE
TGTRLS value mismatch causing errors on some configurations

### ISSUE THREAD

**Issue by rgala** [sitemule/ILEastic#140]
On some configurations the default TGTRLS is *PRV. This is causing compilation errors when module was compiled with *CURRENT, for example:

> Message ID . . . . . . :   CPD5CF2                                            
> Date sent  . . . . . . :   24-06-26      Time sent  . . . . . . :   15:08:34  
>                                                                               
> Message . . . . :   Module OAPIMODGEN has an earliest release of V7R4M0 which 
>   is more recent than the specified target release of V7R3M0.                 
>                                                                               
> Cause . . . . . :   Module OAPIMODGEN in library ILEASTIC has an earliest     
>   release of V7R4M0 which is more recent than the specified target release of 
>   V7R3M0. The module may not have been created for the specified target       
>   release or the observable data has been removed from the module.            
> Recovery  . . . :   Make one of the following changes and run the command     
>   again:                                                                      
>     Specify a more recent target release value on the create command.         
>     Create the module OAPIMODGEN and specify the desired target release value.    

               
TGTRLS on CRTPGM should match the one that were set on modules. 

PR that fixes the issue - https://github.com/sitemule/ILEastic/pull/139

**Comment by m1h43l** [comment]
PR merged.
