### ISSUE TITLE
Authentication required for OPTIONS method

### ISSUE THREAD

**Issue by rgala** [sitemule/ILEastic#148]
While working on improving the CORS plugin I encountered an issue with JWT plugin which returns 401 for preflight requests sent from browsers. According to this https://fetch.spec.whatwg.org/#cors-protocol-and-credentials, preflight requests never include credentials.

Fix proposal: https://github.com/sitemule/ILEastic/pull/147

**Comment by m1h43l** [comment]
If you want to handle preflight request then you can easily do this without any change in the JWT plugin. Just register your CORS plugin before JWT plugin and handle the request in your CORS plugin. Don't pass the request down the chain and you are done.

**Comment by rgala** [comment]
How to do it? Return *off from a method of the plugin?

**Comment by m1h43l** [comment]
https://champions.rpgnextgen.com/Web_Services/Plugins.html

**Comment by rgala** [comment]
Thanks. It looks promising, but I'm afraid that breaking chain in some situations may not be solution, for example, when there is a need to do some additional processing of preflight request after cors plugin.

**Comment by m1h43l** [comment]
Having OPTIONS requests generally pass through is not a good idea. Other people may use OPTIONS for different things.

If you want to offer some custom processing for a preflight request then this should be part of the CORS plugin. Just define a procedure interface which the user can implement and offer a setter procedure for passing a procedure pointer to the CORS plugin. If a procedure pointer for a custom processing procedure is set in the CORS plugin then it can be executed when a request comes in.

That may sound like work but it actually isn't. And it would be the right place to do it.

**Comment by rgala** [comment]
I created a PR for updated cors plugin. Please take a look - https://github.com/sitemule/ILEastic/pull/149

**Comment by m1h43l** [comment]
I think the last PR resolved this issue, so I will close this.
