### ISSUE TITLE
Feature request: Serve static files or directory

### ISSUE THREAD

**Issue by WorksOfLiam** [sitemule/ILEastic#2]
Like express can, ILEastic should provide a way to serve static files or directories.

I was thinking something like: 

* `il_staticFile`
* `il_staticDir`

For example:

```
dcl-proc myservlet;

    dcl-pi *n;
        request  likeds(REQUESTDS);
        response likeds(RESPONSEDS);
    end-pi;

    Select;
        When (request.endpoint = '/'); //Index
            il_staticFile('./path/to/file.html');

        When (%Subst(request.endpoint:1:6) = '/other'); // - /other/file.html
            il_staticDir(request:'./path/to/');
    Endsel;

end-proc;
```

This idea obviously requires routing (#1).

**Comment by NielsLiisberg** [comment]
Absolutley - this is the hole idea !! except it will require you to forward the request and response pointers for static files

also the usages of reqexp to deterning the routing.

Both features a on its way from the icebreak core - stay tuned

**Comment by NielsLiisberg** [comment]
Static files are now supported .

**Comment by NielsLiisberg** [comment]
ile_serveStatic is implementet
