### ISSUE TITLE
Add Basic Auth Plugin

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEastic#28]
As Basic Auth is a very common way for authentication we need a plugin to resolve the username and password from the Authorization HTTP header.

The credentials could be put on the storage map for the request by this we would decouple the parsing of the HTTP header from the authentication mechanism (which could be a user account, validation list, external service, ...). Another plugin for authentication could later pick up the values from the storage map and do the authentication.

If using the storage map for authentication poses a security risk (storing the password in the map) then we could add some configuration for the basic auth plugin and then resolve the authentication function from the config thus keeping it dynamic.

**Comment by m1h43l** [comment]
implemented with pull request #66 , see plugin il_basicauth and il_auth_system

**Comment by NielsLiisberg** [comment]
Great work !!
