### ISSUE TITLE
Improper error handling in program STATICFILE.RPGLE

### ISSUE THREAD

**Issue by tools400** [sitemule/ILEastic#36]
Hi,

Your example program STATICFILE.RPGLE assumes that il_serveStatic() returns *OFF on errors:

```
    // Serve any static files from the IFS
    // if (not il_serveStatic (response : file));   <== Wrong.
    if (il_serveStatic (response : file));   <== Should be
        response.status = 404;
        il_responseWrite(response : 'File ' + file + ' not found');
    endif;
```

In fact il_serveStatic() returns *ON on errors and *OFF on success.
Please fix STATICFILE.RPGLE to correctly check for errors.

Regards,

Thomas.

**Comment by p-behr** [comment]
Should the RPG be changed to expect different return values, or should il_serveStatic be changed to return different values?  Seems the RPG code would read better the way it is, but that conflicts with C wanting to return 0 for success.  Is there maybe a third option that I am not seeing?

**Comment by WorksOfLiam** [comment]
I agree with Patrick that `0` for no error should be correct.

This is a question for @NielsLiisberg as he implemented it.

**Comment by p-behr** [comment]
I have a fix for this issue, and I tested it.  I don't yet know how to go about getting an RPGUnit test for this though.

**Comment by m1h43l** [comment]
You can create a unit test for this by providing a stream file and manually building a response "object". Then create a module with a mock "putChunk" function/procedure (perhaps in the unit test module) which does nothing. Then you could call the API and test it with a valid filename for *on return value and with a non-existing filename for *off.

Just make sure not to include the ILEASTIC module into the unit test service program as it contains the original putChunk function.

Easy ... =)

**Comment by m1h43l** [comment]
Is this issue still open or fixed with the merge of the pull request?

**Comment by p-behr** [comment]
> Is this issue still open or fixed with the merge of the pull request?

I thought it was fixed with the merge of the pull request...but could be mistaken.

**Comment by NielsLiisberg** [comment]
The example is fixed and now use a constant FILE_NOT_FOUND. The procedure still return *ON for errors.
