### ISSUE TITLE
Obsolete reference to NOXDB

### ISSUE THREAD

**Issue by tools400** [sitemule/ILEastic#37]
Hi,

I received the following error message, when attempting to install the example programs:
`liblist: 001-0081 Fehler CPF2110 gefunden beim Hinzufügen von Bibliothek NOXDB in Bibliotheksliste.`

Please remove references to NOXDB from the make file of the example programs, because it seems, that NOXDB is not or no longer required. Or am I missing something? At least I could install the example programs without NOXDB.

Regards,

Thomas.

**Comment by WorksOfLiam** [comment]
Hi @tools400 

I will close this issue and it's believed to be resolved.

Cheers,
Liam
