### ISSUE TITLE
Feature request: determine request method

### ISSUE THREAD

**Issue by WorksOfLiam** [sitemule/ILEastic#4]
In a servlet `REQUEST`/`requestDS`, there should be a way to determine the request type:

```
dcl-proc myservlet;

    dcl-pi *n;
        request  likeds(REQUESTDS);
        response likeds(RESPONSEDS);
    end-pi;

    printf(request.endpoint);
    printf(request.method); //GET, POST, etc

end-proc;
```

Of course, if it is `PUT`, there needs to be a way to get content of the body. (`il_getBody(request)` ???)

**Comment by WorksOfLiam** [comment]
Just to keep note, `request.method` was added in 46e327eb5684b67ae610ff3041a6aa4c5e9bc192.

* https://github.com/NielsLiisberg/ILEastic/commit/46e327eb5684b67ae610ff3041a6aa4c5e9bc192#diff-31f80c15f7e9f88d7f242068acadb407R141

**Comment by m1h43l** [comment]
IMHO this should be moved to the registering of the endpoint and the routing else you would do a "second" routing inside your endpoint code **for every endpoint**  manually.

Having the info in the request ds is ok but the routing should be done automatically.

**Comment by m1h43l** [comment]
There are functions for getting the request method (`il_getRequestMethod`) and for the request body (`il_getContent`) so this issue can be closed.
