### ISSUE TITLE
Error on BIND step, because JSONXML is missing

### ISSUE THREAD

**Issue by tools400** [sitemule/ILEastic#59]
The BIND step fails on the CRTSRVPGM command, because parameter BNDSRVPGM lists service program JSONXML, which is not part of the repository or any other repository referenced by .gitmodules.
For now, removing JSONXML from the CRTSRVPGM command solved the problem.

**Comment by m1h43l** [comment]
JSONXML is needed for the thread local storage. The problem is that it is build in the noxDB submodule but on the CRTSRVPGM command it is not qualified with the library. It should work if you first build noxDB and then adjust the CRTSRVPGM command parameter of both service programs (Going through that myself =) )

**Comment by tools400** [comment]
OK guys. I am about to give up. Since gmake does not work (maybe it is too old and I am not allowed to use YUM), I created ILEASTIC by hand. Of course I spend no thoughts at ILEfastCGI and noxDB but used the existing service programs instead of the previous ILEasctic version.
Lession learned: If you can not re-create the original development environment, keep away.

**Comment by NielsLiisberg** [comment]
Sorry to hear that - I will recreate the complete environment allowing  standard make - hopefully tomorrow - I let you know ...

Remember that ILEastic will use submodules - so if you are trying to do it "non standard" the atleast clone all the submodules before moving the files to the IFS .... but let me just try the process before you are wasting more time.....

**Comment by tools400** [comment]
Hi Niels, changing the project to use standard MAKE would make (escpecially) my live much easier and strengthen my motivation to evaluate and probably use ILEastic.

**Comment by NielsLiisberg** [comment]
To get you started: why don’t you just copy the gmake from an other partition and put it in your “bin” folder. It have no .so as far I remember

**Comment by sjmorales** [comment]
I too had to result to manually run the CRTSVRPGM command to get it to compile.  When you gmake FastCGI and noxDB, they are created in their own libraries and the make file uses the ILEastic library.  It took me quite a while to figure it out.

**Comment by NielsLiisberg** [comment]
Strange - The object library are given by the passed parameter on the gmake
command. I will have a look

**Comment by m1h43l** [comment]
There are two variables in the makefile which can be overridden which helps in this case:

BIN_LIB : the library where the objects are build

BIND_LIB : the library specified where to look for the service programs which are bound and also the library for the binding directory entries.

In my normal development I use the same library for both so my make command looks like:

    make BIN_LIB=ILEASTICMS BIND_LIB=ILEASTICMS

This is no perfect solution but it works and should suffice for the moment.

**Comment by NielsLiisberg** [comment]
BIN_LIB is set now for git submodules, so JSONXML and FASTCGI is build in ILEASTIC library. However this requires you use gmake, since it alone allows you to specify the shell you use and the library list can only be set by QSH shell
