### ISSUE TITLE
Add support for JWT

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEastic#61]
Add native support for JSON Web Tokens.

**Comment by NielsLiisberg** [comment]
I have the code made for IceBreak, that have a slightly diffrent toolbox -  but maybe you will give it a try to make this plug in - it is RPG:

[jwtsample.rpgle.txt](https://github.com/sitemule/ILEastic/files/3088780/jwtsample.rpgle.txt)

**Comment by m1h43l** [comment]
For token verification it seems that Qc3CalculateHMAC can be used as it supports the passing of a key to the hash generation (which Qc3CalculateHash does not support).

**Comment by worksofliam** [comment]
What is the status of the JWT support?

**Comment by m1h43l** [comment]
I have a rudimentary example of JWT with HS256 working. It will get into the repo after BasicAuth has been added/pulled.

**Comment by m1h43l** [comment]
A service program for JWT and a JWT plugin has been added to the repo, see PR #69 ,
