### ISSUE TITLE
Remove submodules from repo

### ISSUE THREAD

**Issue by worksofliam** [sitemule/ILEastic#65]
Does the repository need the two submodules?

* `ILEfastCGI`
* `noxDB`

Can these be removed?

Thanks!

**Comment by m1h43l** [comment]
Why would you want to remove the submodules?

**Comment by NielsLiisberg** [comment]
I am not a big fan of submodules, however, this is how ILEastic gets its resources for now. And There is a dependency on ILEfastCGI - i was thinking of just glue it into ILEastic, but I have had no time to do so.

Regarding noxDB ... I am still in doubt, if the dependency is right in the ILEastic or if it would be more clean if it was in the user application ...

**Comment by m1h43l** [comment]
> Regarding noxDB ... I am still in doubt, if the dependency is right in the ILEastic or if it would be more clean if it was in the user application ...

Currently threadmem will be a noxDB graph. So it is a dependency of ILEastic. I would even go the other way round. We don't need the full API of noxDB for the users. They just add and remove a value (mostly strings and ints). So I would make an API in ILEastic which then calls noxDB API. This way the user only has ILEastic as a direct dependency for their applications. Makes it easier for the user.

**Comment by NielsLiisberg** [comment]
.. And this is my key concern: What if the usercode use version xxx of
noxDB and ILEastic is build with version yyy. So eiter the full monty - or
none ...

if it only is fro key/value then ILEastic already have "SIMPLE_LIST"

The real magic of noxDB it the SQL resultset, and responseWriteJson ,,,

I'm in doubt!!

**Comment by worksofliam** [comment]
Hello

Yes, I see that the `makefile` has been updated to include noxDB and the fast CGI bit.

Perhaps there should be a flag just to build ILEastic without the other two modules.

I will close this issue.
