### ISSUE TITLE
Issue with `request.queryString` contents

### ISSUE THREAD

**Issue by WorksOfLiam** [sitemule/ILEastic#7]
Hi

In PR #6, I committed `demo03.rpgle`. While it is working code, it does show a bug with the `request.queryString` contents.

If you compile `demo03.rpgle`, start the program and then send a request to `http://host:13337/helloworld/howareyou?hello=yes`, this is the response:

```
method: GET
url: /helloworld/howareyou?hello=yes
resource: /helloworld/howareyou
queryString: ?hello=yes HTTP/1.1 Host: 10.1.
protocol: HTTP/1.1
content: 
contentType: 
counter : 1 
counter : 2 
counter : 3 
counter : 4 
counter : 5 
counter : 6 
counter : 7 
counter : 8 
counter : 9 
counter : 10 
```

As you can see, I am seeing the `queryString` as I'm expecting, but it looks like the protocol is appended on the end.

Is this expected or is this a bug?

**Comment by NielsLiisberg** [comment]
Got it ...  and also the protocol level is an error ... can not be in querystring ... 

Thanx

**Comment by m1h43l** [comment]
Is this fixed (I haven't seen this in my test cases)? Can this issue be closed?

**Comment by WorksOfLiam** [comment]
@m1h43l 

If the test cases are passing, then I guess it can be closed. :)

**Comment by m1h43l** [comment]
@WorksOfLiam Only the project owner and the issue creator can close the issue.
