### ISSUE TITLE
Feature Request: HTTP-Patch

### ISSUE THREAD

**Issue by iiSiggi** [sitemule/ILEastic#74]
Good morning,
I´m pretty excited about your project, but i was wondering that GET, PUT,POST, and DELETE are the only supported HTTP-methods. Would it be possible to support the other methods defined in RFC7231 and RFC5789 in a future release?

**Comment by m1h43l** [comment]
HEAD, OPTIONS and PATCH are already coded into the ILEastic. Those constants are just missing in the RPG copybook. I will add the constants.

**Comment by iiSiggi** [comment]
Thanks a lot.

**Comment by NielsLiisberg** [comment]
Beautiful work Mic!! 10 hours and @iiSiggi has the new version !! amazing 👍

**Comment by m1h43l** [comment]
You won't get such a good response time in a commercial environment =) ;-)
