### ISSUE TITLE
Issue building

### ISSUE THREAD

**Issue by wimjongman** [sitemule/ILEastic#81]
I have an issue building. When I run with qsh (per default in the makefile) it fails fast with "gmake not found". If I run with bash then it does everything fine but in the end, the ILEASTIC service program is not created because command "liblist" is not found.  

I solved it by changing 

      BIND_LIB=$(BIN_LIB)
      # The shell we use
      # SHELL=/QOpenSys/usr/bin/qsh
      #         liblist -a $(LIBLIST);\

Out of the box, the script does not finish (in my environment at least but I tried to keep everything as default).

**Comment by NielsLiisberg** [comment]
"liblist" is a feature of QSH and is required if you will not "hard bind" to a library. I suggest you use bash  and gmake as described

**Comment by wimjongman** [comment]
Yes, it makes sense to "liblist". I'm just worried about people that have the same experience.

I wonder why gmake is not available once the shell is switched to qsh. Do you see this too?

**Comment by NielsLiisberg** [comment]
Ahh!! maybe it is because i have  put the open source tools in my path: 

export PATH=$PATH:/QOpenSys/pkgs/bin
PATH=/QOpenSys/pkgs/bin:$PATH

.. Let me investigate that. It would explain it.

Thank you for the feedback Wim

**Comment by openmax** [comment]
i just modify my "/etc/profile" adding to the PATH '/QOpenSys/pkgs/bin" and then i restart *SSHD service
ENDTCPSVR *SSHD 
STRTCPSVR *SSHD 
now QSH inside putty have the new path.

**Comment by m1h43l** [comment]
Can we close this issue?

**Comment by wimjongman** [comment]
The script assumes that '/QOpenSys/pkgs/bin' is in the QSH path which is not the case by default.

**Comment by m1h43l** [comment]
> I have an issue building. When I run with qsh (per default in the makefile) it fails fast with "gmake not found". If I run with bash then it does everything fine but in the end, the ILEASTIC service program is not created because command "liblist" is not found.
> 
> I solved it by changing
> 
> ```
>   BIND_LIB=$(BIN_LIB)
>   # The shell we use
>   # SHELL=/QOpenSys/usr/bin/qsh
>   #         liblist -a $(LIBLIST);\
> ```
> 
> Out of the box, the script does not finish (in my environment at least but I tried to keep everything as default).

If you need to change the shell used in the makefile just pass it on the command line. It will overwrite the one specified in the makefile as SHELL is just a variable.

```
gmake SHELL=/my/path/to/qsh
```

There is no need to change the makefile itself.

If this does not fix your problem please reopen this issue.

**Comment by m1h43l** [comment]
If you want to overwrite BIND_LIB you can this by passing it as a parameter to the make command:

```
gmake BIN_LIB=MYINSTLIB BIND_LIB=MYINSTLIB
```
