### ISSUE TITLE
Simplify sending just a status

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEastic#82]
In many cases you just need to send a HTTP status back to the caller without any content. Currently you must do the following:

```
  response.status = IL_HTTP_NO_CONTENT;
  il_responseWrite(response : '');
```
It would be much better to have that in one call.
```
il_responseWriteStatus(response : IL_HTTP_NO_CONTENT);
```

**Comment by NielsLiisberg** [comment]
You should be able to do


response.status = IL_HTTP_NO_CONTENT;

return


.. otherwise it is a bug

**Comment by m1h43l** [comment]
Ok. That works (probably ... haven't tested) but that is not obvious for the user. That only works because ILEastic sends a "finishing" chunk to the client and that finishing chunk uses the status of the response.

With `response.status = 204` you have set a value but didn't take any obvious action for the user. I am voting for something like already proposed in this issue.

**Comment by m1h43l** [comment]
Won't implement.
