### ISSUE TITLE
Add id for endpoint to request

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEastic#85]
Currently it is not possible in a plugin to identify which endpoint/route is serving the request. It would be nice to be able to add an identifier to the `il_addRoute` function and add that to the request data structure so that the plugin can access it and act dynamically to that value.

Use case: Have a plugin that adds CORS header corresponding to the endpoints used based on a provided configuration.

**Comment by NielsLiisberg** [comment]
Routing now allows  parameter:
 
`il_addRoute(config : %paddr(test1) : IL_ANY : '/simpletest/{myId}/list/{myNum
`
Look in examples **routeparms.rpgle**
