### ISSUE TITLE
Path parameter binding not working if parameter is in middle of URL

### ISSUE THREAD

**Issue by m1h43l** [sitemule/ILEastic#89]
`il_addRoute(config : %paddr(getProperty) : IL_GET : '^\/api\/mapping\/[^\/]+/{property}$');`

with the following URL:  http://host:44000/api/mapping/16/value/dummy

results in a parameter binding for _property_ of "value/dummy"

In this case as the path parameter should be the last segment of the URL is should have resulted in not finding any route as this route does not match the URL.

**Comment by NielsLiisberg** [comment]
1) Don't think you have to escape /
2) I think it is that ^ issues ...

**Comment by m1h43l** [comment]
I think the issue is in this line : https://github.com/sitemule/ILEastic/blob/master/src/api.c#L359

The named parameter is replaced with `(.*)` but this also includes the forward slash. It seems to work if we exclude the forward slash like this `([^/]+)` and we want to have at least one character thus the +.

**Comment by NielsLiisberg** [comment]
Correct. My implementation is not perfect

fre. 14. aug. 2020 kl. 15.57 skrev m1h43l <notifications@github.com>:

**Comment by m1h43l** [comment]
Works now. Thanks.
