### ISSUE TITLE
Example from Read.me don't work -> Pointer not set for location referenced

### ISSUE THREAD

**Issue by jsranko** [sitemule/ILEastic#95]
Additional Message Information                      
                                                                             
 Message ID . . . . . . :   MCH3601       Severity . . . . . . . :   40      
 Message type . . . . . :   Escape                                           
 Date sent  . . . . . . :   11/27/20      Time sent  . . . . . . :   11:08:24
                                                                             
 Message . . . . :   Pointer not set for location referenced.                
 Cause . . . . . :   A pointer was used, either directly or as a basing      
   pointer, that has not been set to an address.                             

                            Display Message Details                          
                                                                             
 Message ID . . . . . . :   MCH3601       Severity . . . . . . . :   40      
 Date sent  . . . . . . :   11/27/20      Time sent  . . . . . . :   11:08:24
 Message type . . . . . :   Escape                                           
 From . . . . . . . . . :   CECUSER       CCSID  . . . . . . . . :   65535   
                                                                             
 From program . . . . . . . . . :   ILEASTIC                                 
   From library . . . . . . . . :     ILEASTIC                               
   From module  . . . . . . . . :     ILEASTIC                               
   From procedure . . . . . . . :     findRoute                              
   From statement . . . . . . . :     10                                     
                                                                             
 To program . . . . . . . . . . :   ILEASTIC                                 
   To library . . . . . . . . . :     ILEASTIC                               
   To module  . . . . . . . . . :     ILEASTIC                               
   To procedure . . . . . . . . :     findRoute                              
   To statement . . . . . . . . :     10

**Comment by NielsLiisberg** [comment]
@jsranko thank you for the observation - I have to update the read.me for sure .. also the text btw.  However, can you manage to get the examples in the examples folder to work?

**Comment by jsranko** [comment]
No I have not tried. The program has only 3 lines. Can I do so much wrong?

// -----------------------------------------------------------------------------
// Main
// -----------------------------------------------------------------------------
dcl-proc main;

    dcl-ds config likeds(IL_CONFIG);

    config.port = $(ILEASTIC_PORT);
    config.host = '*ANY';

    il_listen (config : %paddr(myservlet));

end-proc;
// -----------------------------------------------------------------------------
// Servlet call back implementation
// -----------------------------------------------------------------------------
dcl-proc myservlet;

    dcl-pi *n;
        request  likeds(IL_REQUEST);
        response likeds(IL_RESPONSE);
    end-pi;
    dcl-s pJson Pointer;
    dcl-s pFileData Pointer;
    dcl-s fileName varchar(50);
    dcl-s fileSize varchar(50) inz('1k');
    dcl-s output varchar(32000);

    il_responseWrite(response:output);

end-proc;

**Comment by m1h43l** [comment]
The message you get sounds a bit like like bug #88 which has been fixed.

...

It seems this bug is still there if you don't use `il_addRoute` but pass the servlet procedure directly on `il_listen`.

If you change your code to:

```
  il_addRoute(config : %paddr(myservlet) : IL_GET);
  
  il_listen(config);
```

It worksed for me.

**Comment by NielsLiisberg** [comment]
OK - I can reproduce it now. 

I always use the router - so I did not see this - nor is it in the regression test.

thanx for the input.
